on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test:no-reloading
  release:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build & push docker image
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: autotwitter
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          addLatest: true